/*
 * inno_common_mode_tbls.c - Innodisk Common Function
 *
 * Copyright (c) 2022-2024, Innodisk CORPORATION.  All rights reserved.
 * All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "inno_debug.h"
#include "inno_common.h"
#include "inno_common_reg.h"
#include "inno_common_data.h"
#include "inno_common_mode_tbls.h"

INNO_COMM_REG_8 inno_comm_mode_common_8[] = {
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_8 inno_comm_start_stream_8[] = {
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_START},
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_STREAM},
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_8 inno_comm_stop_stream_8[] = {
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_STOP},
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_STREAM},
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_0[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(0)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_1[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(1)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_2[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(2)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_3[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(3)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_4[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(4)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_5[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(5)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_6[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(6)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_sensor_mode_7[] = {
	{PREVIEW_SENSOR_MODE,		SENSOR_MODE(7)}								// PREVIEW_SENSOR_MODE
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_640x480_60fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_640)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_480)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_60},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_640x480_90fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_640)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_480)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_90},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_90))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_90))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_640x480_120fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_640)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_480)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_120},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_120))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_120))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_1280x720_60fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_1280)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_720)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_60},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_1280x720_90fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_1280)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_720)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_90},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_90))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_90))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_1280x720_120fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_1280)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_720)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_120},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_120))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_120))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_1920x1080_50fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_1920)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_1080)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_50},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_50))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_50))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_1920x1080_60fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_1920)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_1080)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_60},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_1920x1200_50fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_1920)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_1200)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_50},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_50))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_50))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_1920x1200_60fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_1920)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_1200)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_60},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_60))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_3840x2160_25fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_3840)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_2160)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_25},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_25))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_25))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_3840x2160_30fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_3840)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_2160)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_30},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_30))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_30))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_4096x3120_10fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_4096)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_3120)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_10},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_10))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_10))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_4096x3120_20fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_4096)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_3120)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_20},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_20))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_20))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_4192x3120_10fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_4192)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_3120)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_10},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_10))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_10))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_evxm_oymz_mode_4192x3120_20fps[] = {
	{ATOMIC,					INNO_SWAP16(ATOMIC_RECORD)},				// ATOMIC
	{PREVIEW_WIDTH,				INNO_SWAP16(INNO_WIDTH_4192)},				// PREVIEW_WIDTH
	{PREVIEW_HEIGHT,			INNO_SWAP16(INNO_HEIGHT_3120)},				// PREVIEW_HEIGHT
	{ATOMIC,					INNO_SWAP16(ATOMIC_UPDATE_ALL)},			// ATOMIC
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
	{PREVIEW_MAX_FPS,			INNO_FPS_20},								// PREVIEW_MAX_FPS
	{REVIEW_AE_MAX_ET,			INNO_SWAP32_LSB(AE_MAX_ET(INNO_FPS_20))},	// PREVIEW_AE_MAX_ET
	{REVIEW_AE_MAX_ET + 0x0002,	INNO_SWAP32_MSB(AE_MAX_ET(INNO_FPS_20))},	// PREVIEW_AE_MAX_ET
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#if INNO_PREVIEW_OUT_FMT_EN
	{PREVIEW_OUT_FMT,			PREVIEW_OUT_FMT_YUV_JFIF_422},				// PREVIEW_OUT_FMT
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_MODE},
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_comm_mode_common_16[] = {
#if INNO_SYS_START_EN
	{SYS_START,					INNO_SWAP16(SYS_START_COMMON)},				// SYS_START
#endif
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_comm_start_stream_16[] = {
#if INNO_SYS_START_EN
	{SYS_START,					INNO_SWAP16(SYS_START_START_STREAM)},		// SYS_START
#endif
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_START},
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_STREAM},
	{INNO_COMM_TABLE_END,		0x00}
};

INNO_COMM_REG_16 inno_comm_stop_stream_16[] = {
#if INNO_SYS_START_EN
	{SYS_START,					INNO_SWAP16(SYS_START_STOP_STREAM)},		// SYS_START
#endif
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_STOP},
	{INNO_COMM_TABLE_WAIT_MS,	INNO_COMM_WAIT_MS_STREAM},
	{INNO_COMM_TABLE_END,		0x00}
};

const int inno_comm_10fps[] = {
	INNO_FPS_10,
};

const int inno_comm_15fps[] = {
	INNO_FPS_15,
};

const int inno_comm_20fps[] = {
	INNO_FPS_20,
};

const int inno_comm_25fps[] = {
	INNO_FPS_25,
};

const int inno_comm_30fps[] = {
	INNO_FPS_30,
};

const int inno_comm_50fps[] = {
	INNO_FPS_50,
};

const int inno_comm_60fps[] = {
	INNO_FPS_60,
};

const int inno_comm_90fps[] = {
	INNO_FPS_90,
};

const int inno_comm_120fps[] = {
	INNO_FPS_120,
};
